---
kind: pipeline
name: build and publish co-op cloud wizard
steps:
  - name: build and publish image
    image: plugins/docker@sha256:7a8e188c7dcaf15842d2a0bc22bf08d16f6a01279d8bb53c26f58afa17748458
    settings:
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: git.coopcloud.tech/toolshed/coop-cloud-backend
      registry: git.coopcloud.tech

trigger:
  event:
  - push
  - tag
  branch:
  - main
