---
kind: pipeline
name: build and publish co-op cloud wizard
steps:
  - name: build and publish image
    image: plugins/docker
    settings:
      auto_tag: true
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: git.coopcloud.tech/toolshed/coop-cloud-backend
      registry: git.coopcloud.tech

trigger:
  event:
  - push
  - tag
  branch:
  - main
